version: '3'
services:
  db:
    container_name: lotterydb
    build:
      # dockerfileの名前だけ指定する
      dockerfile: Dockerfile
      # contextで場所を指定する
      context: ./postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
        - .:/code
  web:
    container_name: lottery
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  dbvolume: